![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [5]:
my_array = np.arange(10)
print(my_array)
print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [8]:
print(my_array)
print(my_array[-2:-4:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


In [9]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [15]:
print(my_array)
print(my_array[-8::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [19]:
my_matrix = np.arange(1,21).reshape((4,5))
my_matrix

print(my_matrix[::-1, ::-1]) 

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [20]:
np.flip(my_matrix)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [23]:

# print(my_matrix)

print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [28]:
my_matrix


my_matrix[::2, ::2]




array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [31]:
my_matrix 

print(my_matrix[:-1:, ::-1])



[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [36]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)

filtrado = x[x == 'Loro'] 
print(filtrado)

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']
['Loro' 'Loro']


In [39]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)

mask = np.array([True, False, False, True,False]) 
mask = x == 'Loro'

x[mask]

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


array(['Loro', 'Loro'], dtype='<U5')

In [41]:
x[np.where(x =="Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [44]:
np.extract(x == "Loro" , x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [47]:
x = np.arange(20).reshape((2,5,2))

print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10 (es el mismo)
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [49]:
my_matrix

print(my_matrix[::-1 ,::-1])

np.flip(my_matrix)


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [57]:
x = np.zeros(10)
print(x)

print(x.itemsize)
print(x.nbytes)

x[3] = -1

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
80
[ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [60]:
x = np.arange(10,50)
print(x) 

print(np.flip(x))

print(x[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [61]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [93]:
x = np.random.randint(1,100, size = (10,10)) 
print(x)

print(x.min())

print(x.max())

[[39 22 55 13 21 26 30 14 31 51]
 [64 41 10 43 62 90  5 68 52 58]
 [57 37 58 47 88 98 55 65 88 56]
 [33 19 24 65 80 98 33 14 80 92]
 [65 11 23 99 45 93 52  1  1 93]
 [49 34 18 54  4 60 37 26 77 46]
 [66 68 94 68 92 70 30 79 66 79]
 [67 22 80  6 52 24 74 78 91 56]
 [ 9 11 87 12 75 32 18 63 46  3]
 [99 18 74 34 96 82  5 67 50 34]]
1
99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [95]:
x = np.random.random(30) 
print(x)
m = x.mean()
print(m)

[0.44078813 0.78539059 0.73416606 0.15628188 0.11569478 0.12894218
 0.08453743 0.45796391 0.12808051 0.56635199 0.62111774 0.4230415
 0.01295324 0.57222974 0.45961593 0.27583016 0.51864194 0.65503314
 0.66626514 0.26383126 0.47630768 0.5298258  0.93568062 0.94737481
 0.95125732 0.91965857 0.72100309 0.66195265 0.93648021 0.17285145]
0.5106383153969144


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [99]:
x = np.ones((10,10))
#print(x)

x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [103]:
x = np.zeros((10,10))
#print(x) 

x[0:10:9] = 1 
x.T[0:10:9] = 1 
print(x) 


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [111]:
x = np.zeros((8,8), dtype = int)
#print(x)

x[1::2,::2] = 1 
x[::2,1::2] = 1

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [116]:
x = np.tile(np.array([[0,1],[1,0]]), (4,4))

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [119]:
x = np.random.randint(1,20,(5,5)) 
#print(x)

x =(x-np.mean(x)) / np.std(x) 

print(x)

[[-0.19202384 -1.53619075  1.3441669   0.76809537  0.76809537]
 [-1.15214306  0.38404769  0.96011922 -0.96011922  1.3441669 ]
 [-0.19202384 -0.76809537  0.57607153 -0.38404769 -1.3441669 ]
 [ 1.53619075 -0.38404769  0.38404769  0.57607153  0.76809537]
 [-0.19202384  1.53619075 -0.76809537 -1.15214306 -1.92023843]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [129]:
x = np.arange(11) 
#print(x)

y = x.copy() 
#print(y) 
x[4:9] =-1 

print(x)
print(y) 

z = y.copy()
z[3:9] = -z[3:9]
print(z)

[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
